module TestFailTryDrop2 {
   err X;

   fun TestFunApply[<Drop> A](consume a:A):() {
       b = a;
       () = try {
           return;
       } catch {
         .X => {
          discard(b);
         };
       };
       return;
   };
}