module TestFailTryReturnDrop2 {
   err X;

   fun TestFunApply[<Copy, Drop> A](consume a:A):(c:A) {
       c = try {
           b = a;
           return b;
       } catch {
         .X => {
           b = a;
           discard b;
           return b;
         };
       };
       return c;
   };
}