module TestFailTryDoubleReturn {
   err X;

   fun TestFunApply[<Copy> A](consume a:A):(d:A,e:A) {
       (d,e) = try {
          b = a;
          return (b,b);
       } catch {
         .X => {
           b = a;
           c = copy b;
           return (b,c);
         };
       };
       return (d,e);
   };
}